version: "3"
services:
  server:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config: 
        parallelism: 2
        delay: 15s
    build: .
    image: georgefront2022/admin-docker:latest
    volumes: 
      - upload-files:/home/nodejs/server/public/upload
    command: npm run start
    environment:
      - NODE_ENV=production
      - MONGO_IP=${MONGO_IP}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - mongodb

  nginx:
    image: nginx:1.19
    links:
      - server
    ports:
      - "80:80"
    volumes:
      - ./client:/home/client      
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  mongodb:
    image: mongo:4.2
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./mongoDB_file:/home/mongoDB_file
      - mongo-db:/data/db
    command: mongod
    
  # redis:
  #   image: redis:6.0.14

volumes: 
  mongo-db:
  upload-files:

    