version: "3"
services:
  server:
    build: .
    command: npm run dev
    depends_on:
      - mongodb
    volumes:
      - ./server:/home/nodejs/server
      - ./server/node_modules

  nginx:
    image: nginx:1.19   
    linkes:
      - server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mongodb:
    image: mongo:4
    command: mongod
    volumes:
      - ./mongoDB_file:/home/mongoDB_file
      - mongo-db:/data/db
    ports:
      - "27017:27017"
  

volumes:
  mongo-db:
